version: '3.3'
services: 
    api:
        build: .
        ports: 
            - 3000:3000
        depends_on: 
            - mongo

    mongo:
        container_name: tel335_mongo
        image: mongo:latest
        ports: 
            - 27017:27017
        volumes: 
            - ../mongo_data:/data/db